package com.pet.project.kafkadynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pet.project.kafkadynamodb.converter.LocalDateTimeConverter;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@NoArgsConstructor
@AllArgsConstructor
@JsonDeserialize(using = com.pet.project.kafkadynamodb.util.json.CarInfoDeserializer.class)
@DynamoDBTable(tableName = "CarInfo")
public class CarInfo {
    private String carModel;
    private boolean isReserved;
    private String renterName;
    private LocalDateTime dateTime;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getCarModel() {
        return carModel;
    }

    @DynamoDBAttribute
    public boolean getIsReserved() {
        return isReserved;
    }

    @DynamoDBAttribute
    public String getRenterName() {
        return renterName;
    }

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    public LocalDateTime getDateTime() {
        return dateTime;
    }

    public void setCarModel(String carModel) {
        this.carModel = carModel;
    }

    public void setIsReserved(boolean isReserved) {
        this.isReserved = isReserved;
    }

    public void setRenterName(String renterName) {
        this.renterName = renterName;
    }

    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

}
