package com.pet.project.kafkadynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pet.project.kafkadynamodb.converter.LocalDateTimeConverter;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@NoArgsConstructor
@JsonDeserialize(using = com.pet.project.kafkadynamodb.util.json.UserExceptionInfoDeserializer.class)
@DynamoDBTable(tableName = "UserExceptionInfo")
public class UserExceptionInfo {
    private String carModel;
    private String message;
    private LocalDateTime dateTime;

    public UserExceptionInfo(String message, LocalDateTime dateTime) {
        this.message = message;
        this.dateTime = dateTime;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getCarModel() {
        return carModel;
    }

    @DynamoDBAttribute
    public String getMessage() {
        return message;
    }

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    public LocalDateTime getDateTime() {
        return dateTime;
    }

    public void setCarModel(String carModel) {
        this.carModel = carModel;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }
}
